# Generated by Django 2.2.7 on 2019-11-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20191122_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
